<!DOCTYPE html>
<html>

<head>
    <!-- UTF8 -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- External CSS -->
    <link rel="stylesheet" href="styles/styles.css" type="text/css">
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Gotu&display=swap" rel="stylesheet">
    <!-- header title -->
    <title>${requestScope.message}</title>
    <!-- JQuery -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
</head>
<body>
<header>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <div class="text-center">
                    <img src="images/fggf.JPG">
                </div>
            </div>
        </div>
    </div>
</header>
